### ISSUE TITLE
Blue Buss Line

### ISSUE THREAD

**Issue by hekm77** [DSorlov/hasl-platform#33]
Is it possible to add a color of blue buss line to the hasl-departure-card?
https://sv.wikipedia.org/wiki/Blåbusslinje

**Comment by dimmanramone** [comment]
The colors are based on the colors of the official sl website (all the buses there are red there). But yes it possible to add that like an optional variable. Though the Wikipedia link it doesn't seem to be fully updated, because I think that line 50 is a blue bus too, do you have any other source that have all the blue lines?

**Comment by hekm77** [comment]
Probably
https://www.trafiklab.se/api/sl-realtidsinformation-4/sl-realtidsinformation-4
Gemensamt för alla trafikslag > GroupOfLine

**Comment by dimmanramone** [comment]
Ok thanks. I'll look into it.

**Comment by dimmanramone** [comment]
@hekm77 Finally I had some time to take a look on that. I added the GroupOfLine in the sensor data and now I have to update the lovelace card too.

**Comment by hekm77** [comment]
@dimmanramone 
Thank you so much for your work

**Comment by dimmanramone** [comment]
@hekm77 More than welcome to test the blue bus. You can find the update sensor and cards in the dev branch.

https://github.com/DSorlov/hasl-platform/tree/dev

https://github.com/DSorlov/hasl-cards/tree/dev

**Comment by hekm77** [comment]
@dimmanramone 
This is magic.
Thanks.
